version: '2'

services:
  app:
    extends:
      file: ../v3.5/compose/docker-compose.yml
      service: app
  redis:
    extends:
      file: ../v3.5/compose/docker-compose.yml
      service: redis

networks:
  sdnet:
    driver: "bridge"
    
volumes:
  mysqldata:
    driver: "local"
  redisdata:
    driver: "local"